/** Static game data: buildings, jobs, traits, wildlife, ranks. */

import type { BuildingDef, BuildingId, JobId, Rank, SpeciesDef, SpeciesId, TraitId } from '../types';

export const CARRY_CAPACITY = 12;

/** One in-game day at 1× speed, in real seconds. 20 min day + 10 min night. */
export const DAY_LENGTH = 30 * 60;
/** Days per season — 3 real hours at 1× = 6 days. */
export const DAYS_PER_SEASON = 6;

export const RESOURCE_META: Record<string, { name: string; icon: string; color: string }> = {
  wood: { name: 'Wood', icon: '🪵', color: '#b0763f' },
  stone: { name: 'Stone', icon: '🪨', color: '#9aa2ab' },
  wheat: { name: 'Wheat', icon: '🌾', color: '#e0b95c' },
  flour: { name: 'Flour', icon: '🥣', color: '#e8dcc4' },
  bread: { name: 'Bread', icon: '🍞', color: '#c98a4b' },
  coin: { name: 'Coins', icon: '🪙', color: '#f0c860' },
};

export const JOB_META: Record<JobId, { name: string; icon: string; desc: string }> = {
  helper: {
    name: 'Helper',
    icon: '🧺',
    desc: 'Gathers wood and stone by hand, hauls goods between buildings, and helps raise new construction.',
  },
  woodcutter: { name: 'Woodcutter', icon: '🪓', desc: 'Fells trees near the lodge and carries wood to storage.' },
  stoneworker: { name: 'Stoneworker', icon: '⛏️', desc: 'Works the boulders near the quarry for stone.' },
  farmer: { name: 'Farmer', icon: '🌱', desc: 'Sows and harvests the wheat plots around the farm.' },
  miller: { name: 'Miller', icon: '🌬️', desc: 'Grinds wheat into flour at the windmill.' },
  baker: { name: 'Baker', icon: '👩‍🍳', desc: 'Turns flour into bread the whole kingdom eats.' },
  keeper: { name: 'Keeper', icon: '🐾', desc: 'Looks after the kingdom’s animals.' },
};

export const TRAIT_META: Record<TraitId, { name: string; icon: string; desc: string }> = {
  greenThumb: { name: 'Green Thumb', icon: '🌿', desc: 'Crops seem to grow a little faster under their care.' },
  animalFriend: { name: 'Animal Friend', icon: '🐇', desc: 'Wildlife does not startle when they walk past.' },
  crafty: { name: 'Crafty', icon: '🔨', desc: 'Quick and tidy at a workbench or an oven.' },
  curious: { name: 'Curious', icon: '🔍', desc: 'Wanders further than most, and notices things.' },
  earlyRiser: { name: 'Early Riser', icon: '🌅', desc: 'Up before the rest of the kingdom.' },
  nightOwl: { name: 'Night Owl', icon: '🌙', desc: 'Often still out well after dark.' },
  outdoorsy: { name: 'Outdoorsy', icon: '🥾', desc: 'Crosses rough ground as easily as a road.' },
  steady: { name: 'Steady', icon: '🧭', desc: 'Never hurries, never stops. Tires more slowly.' },
};

export const TRAIT_IDS = Object.keys(TRAIT_META) as TraitId[];

export function rankOf(xp: number): Rank {
  if (xp >= 100) return 'Master';
  if (xp >= 75) return 'Expert';
  if (xp >= 50) return 'Journeyman';
  if (xp >= 25) return 'Adept';
  return 'Novice';
}

export const RANK_COLOR: Record<Rank, string> = {
  Novice: '#9aa4b2',
  Adept: '#7ec98f',
  Journeyman: '#6cb6e8',
  Expert: '#c08ce8',
  Master: '#f0c860',
};

/** Skill multiplier applied to work speed. Gentle: 0.8× at novice to 1.4× at master. */
export function skillMul(xp: number): number {
  return 0.8 + (Math.min(100, xp) / 100) * 0.6;
}

/** Experience gained per second of real work. Fast early, slow near mastery. */
export function xpGain(current: number, seconds: number): number {
  const falloff = 1.5 - (Math.min(100, current) / 100) * 1.0;
  return seconds * 0.05 * falloff;
}

export const BUILDINGS: Record<BuildingId, BuildingDef> = {
  campfire: {
    id: 'campfire',
    name: 'Campfire',
    category: 'storage',
    w: 1,
    h: 1,
    cost: {},
    labour: 0,
    maxLevel: 1,
    order: -1,
    desc: 'Where the kingdom began. Holds a little of everything, and never quite goes out.',
    storage: [60],
    housing: [2],
    light: [{ x: 0.5, y: 0.5, radius: 46, color: '#ffb35c' }],
    solid: false,
  },
  shelter: {
    id: 'shelter',
    name: 'Shelter',
    category: 'housing',
    w: 2,
    h: 2,
    cost: { wood: 20 },
    labour: 45,
    maxLevel: 2,
    upgradeCostMul: 2.2,
    order: 0,
    desc: 'A roof, a door, and somewhere dry to sleep. Houses two.',
    housing: [2, 4],
    light: [{ x: 1.0, y: 1.35, radius: 34, color: '#ffc06a' }],
    solid: true,
  },
  cottage: {
    id: 'cottage',
    name: 'Cottage',
    category: 'housing',
    w: 2,
    h: 2,
    cost: { wood: 45, stone: 25 },
    labour: 90,
    maxLevel: 2,
    upgradeCostMul: 2.0,
    order: 1,
    desc: 'Proper walls and a chimney. Houses four, and villagers rest better here.',
    housing: [4, 6],
    unlock: 'cottage',
    light: [{ x: 1.0, y: 1.35, radius: 40, color: '#ffc06a' }],
    solid: true,
  },
  storehouse: {
    id: 'storehouse',
    name: 'Storehouse',
    category: 'storage',
    w: 2,
    h: 2,
    cost: { wood: 25 },
    labour: 40,
    maxLevel: 2,
    upgradeCostMul: 2.4,
    order: 10,
    desc: 'Everything the kingdom keeps ends up here. Build them near where goods are made.',
    storage: [250, 550],
    solid: true,
  },
  lodge: {
    id: 'lodge',
    name: "Woodcutter's Lodge",
    category: 'production',
    w: 2,
    h: 2,
    cost: { wood: 30 },
    labour: 55,
    maxLevel: 2,
    upgradeCostMul: 2.2,
    order: 20,
    desc: 'Woodcutters work the trees nearby. Place it in or beside a wood.',
    slots: [2, 3],
    job: 'woodcutter',
    harvests: 'tree',
    solid: true,
  },
  quarry: {
    id: 'quarry',
    name: 'Quarry',
    category: 'production',
    w: 2,
    h: 2,
    cost: { wood: 30, stone: 10 },
    labour: 60,
    maxLevel: 2,
    upgradeCostMul: 2.2,
    order: 21,
    desc: 'Stoneworkers break the boulders nearby. Place it against rocky ground.',
    slots: [2, 3],
    job: 'stoneworker',
    harvests: 'boulder',
    unlock: 'quarry',
    solid: true,
  },
  farm: {
    id: 'farm',
    name: 'Wheat Farm',
    category: 'production',
    w: 3,
    h: 3,
    cost: { wood: 40, stone: 10 },
    labour: 80,
    maxLevel: 2,
    upgradeCostMul: 2.0,
    order: 22,
    desc: 'A small barn and eight plots. Farmers sow, wait, and harvest wheat.',
    slots: [2, 3],
    job: 'farmer',
    plots: true,
    unlock: 'farm',
    solid: false,
  },
  mill: {
    id: 'mill',
    name: 'Windmill',
    category: 'production',
    w: 2,
    h: 2,
    cost: { wood: 50, stone: 30 },
    labour: 110,
    maxLevel: 2,
    upgradeCostMul: 2.0,
    order: 23,
    desc: 'Grinds wheat into flour. The sails turn whenever the miller is working.',
    slots: [1, 2],
    job: 'miller',
    recipe: { inputs: { wheat: 3 }, outputs: { flour: 2 }, seconds: 18 },
    unlock: 'mill',
    solid: true,
  },
  bakery: {
    id: 'bakery',
    name: 'Bakery',
    category: 'production',
    w: 2,
    h: 2,
    cost: { wood: 40, stone: 40 },
    labour: 120,
    maxLevel: 2,
    upgradeCostMul: 2.0,
    order: 24,
    desc: 'Flour becomes bread. The smell reaches most of the kingdom.',
    slots: [2, 3],
    job: 'baker',
    recipe: { inputs: { flour: 2 }, outputs: { bread: 3 }, seconds: 22 },
    unlock: 'bakery',
    light: [{ x: 1.0, y: 1.3, radius: 42, color: '#ffa14a' }],
    solid: true,
  },
  well: {
    id: 'well',
    name: 'Well',
    category: 'comfort',
    w: 1,
    h: 1,
    cost: { stone: 15 },
    labour: 20,
    maxLevel: 1,
    order: 30,
    desc: 'People gather at wells. Nobody has ever been able to explain why.',
    solid: true,
  },
  bench: {
    id: 'bench',
    name: 'Bench',
    category: 'comfort',
    w: 1,
    h: 1,
    cost: { wood: 6 },
    labour: 6,
    maxLevel: 1,
    order: 31,
    desc: 'Somewhere to sit and not do very much.',
    solid: false,
  },
  lantern: {
    id: 'lantern',
    name: 'Lantern',
    category: 'comfort',
    w: 1,
    h: 1,
    cost: { wood: 4, stone: 3 },
    labour: 8,
    maxLevel: 1,
    order: 32,
    desc: 'Lights a small circle of the kingdom after dark.',
    light: [{ x: 0.5, y: 0.4, radius: 52, color: '#ffbe63' }],
    solid: false,
  },
  flowerbed: {
    id: 'flowerbed',
    name: 'Flower Bed',
    category: 'comfort',
    w: 1,
    h: 1,
    cost: { wood: 3 },
    labour: 6,
    maxLevel: 1,
    order: 33,
    desc: 'Pretty. Certain small creatures have opinions about flowers.',
    solid: false,
  },
  sapling: {
    id: 'sapling',
    name: 'Sapling',
    category: 'comfort',
    w: 1,
    h: 1,
    cost: { wood: 2 },
    labour: 5,
    maxLevel: 1,
    order: 34,
    desc: 'Plant a tree. It will take a while, but it will get there.',
    solid: false,
  },
  statue: {
    id: 'statue',
    name: 'Standing Stone',
    category: 'comfort',
    w: 1,
    h: 1,
    cost: { stone: 40 },
    labour: 40,
    maxLevel: 1,
    order: 35,
    desc: 'Nobody remembers putting it there, which is impressive, because you did.',
    unlock: 'statue',
    solid: true,
  },
};

export const BUILD_ORDER: BuildingId[] = (Object.keys(BUILDINGS) as BuildingId[])
  .filter((k) => k !== 'campfire')
  .sort((a, b) => BUILDINGS[a].order - BUILDINGS[b].order);

export const CATEGORY_META: Record<string, { name: string; icon: string }> = {
  housing: { name: 'Housing', icon: '🏠' },
  storage: { name: 'Storage', icon: '📦' },
  production: { name: 'Production', icon: '⚙️' },
  comfort: { name: 'Comfort', icon: '🌷' },
};

/** How fast a villager crosses each terrain, as a multiplier on base speed. */
export const TERRAIN_SPEED: Record<string, number> = {
  road: 1.95,
  path: 1.45,
  grass: 1.0,
  meadow: 1.0,
  sand: 0.95,
  forest: 0.7,
  rocky: 0.72,
  shallow: 0.45,
  water: 0,
};

export const SPECIES: Record<SpeciesId, SpeciesDef> = {
  rabbit: {
    id: 'rabbit',
    name: 'Rabbit',
    plural: 'Rabbits',
    habitat: { meadow: 1.0, grass: 0.7, forest: 0.2 },
    likesProps: { flowers: 0.8, bush: 0.4 },
    active: [0.02, 0.78],
    density: 0.011,
    hardCap: 7,
    speed: 1.7,
    skittish: 3.2,
    rarity: 1,
    colors: { body: '#b39a80', belly: '#f0e6d8', accent: '#8a7460' },
    hint: 'Rabbits seem to prefer open meadows, especially where flowers grow.',
    size: 1,
  },
  squirrel: {
    id: 'squirrel',
    name: 'Squirrel',
    plural: 'Squirrels',
    habitat: { forest: 1.0, grass: 0.25 },
    likesProps: { tree: 1.2 },
    active: [0.03, 0.72],
    density: 0.013,
    hardCap: 7,
    speed: 2.1,
    skittish: 2.4,
    rarity: 1,
    colors: { body: '#a8622f', belly: '#e8cfae', accent: '#7c451f' },
    hint: 'Squirrels never stray far from standing trees.',
    size: 1,
  },
  bird: {
    id: 'bird',
    name: 'Sparrow',
    plural: 'Sparrows',
    habitat: { grass: 0.7, meadow: 0.8, forest: 0.8, path: 0.4, road: 0.4 },
    likesProps: { tree: 0.5 },
    active: [0.0, 0.7],
    density: 0.014,
    hardCap: 9,
    speed: 2.6,
    skittish: 2.0,
    rarity: 1,
    colors: { body: '#8c7a63', belly: '#e8ddc8', accent: '#4a3f34' },
    hint: 'Sparrows turn up almost anywhere, but they love a farm.',
    size: 0,
  },
  duck: {
    id: 'duck',
    name: 'Duck',
    plural: 'Ducks',
    habitat: { shallow: 1.2, water: 0.9, sand: 0.5 },
    likesProps: { reeds: 0.8, lilypad: 0.6 },
    active: [0.02, 0.8],
    density: 0.05,
    hardCap: 5,
    speed: 1.1,
    skittish: 1.6,
    rarity: 1.4,
    colors: { body: '#5c6b4a', belly: '#e6dcc0', accent: '#e0a83c' },
    hint: 'Ducks arrive wherever there is standing water to sit on.',
    size: 1,
  },
  frog: {
    id: 'frog',
    name: 'Frog',
    plural: 'Frogs',
    habitat: { shallow: 1.4, sand: 0.4 },
    likesProps: { reeds: 1.0, lilypad: 1.4 },
    active: [0.55, 0.98],
    density: 0.045,
    hardCap: 5,
    speed: 0.9,
    skittish: 1.4,
    rarity: 1.6,
    colors: { body: '#6f9c4a', belly: '#d6e2a8', accent: '#3f6030' },
    hint: 'Frogs start up around the water in the evening.',
    size: 0,
    seasons: ['spring', 'summer', 'autumn'],
  },
  butterfly: {
    id: 'butterfly',
    name: 'Butterfly',
    plural: 'Butterflies',
    habitat: { meadow: 1.0, grass: 0.4 },
    likesProps: { flowers: 2.0 },
    active: [0.1, 0.6],
    density: 0.03,
    hardCap: 8,
    speed: 1.5,
    skittish: 0,
    rarity: 1.2,
    colors: { body: '#e8a0c8', belly: '#fff0f6', accent: '#c05c92' },
    hint: 'Butterflies gather wherever flowers are planted.',
    size: 0,
    seasons: ['spring', 'summer'],
  },
  bee: {
    id: 'bee',
    name: 'Bee',
    plural: 'Bees',
    habitat: { meadow: 0.9, grass: 0.3 },
    likesProps: { flowers: 2.2 },
    active: [0.08, 0.62],
    density: 0.03,
    hardCap: 8,
    speed: 2.2,
    skittish: 0,
    rarity: 1.3,
    colors: { body: '#e8c040', belly: '#fff4c0', accent: '#332a18' },
    hint: 'Bees follow the flowers, and seem busier near farmland.',
    size: 0,
    seasons: ['spring', 'summer', 'autumn'],
  },
  deer: {
    id: 'deer',
    name: 'Deer',
    plural: 'Deer',
    habitat: { forest: 1.2, meadow: 0.4 },
    likesProps: { tree: 0.7, bush: 0.5 },
    active: [0.0, 0.14],
    density: 0.008,
    hardCap: 3,
    speed: 1.5,
    skittish: 6.5,
    rarity: 2.6,
    colors: { body: '#a87a4c', belly: '#e8d2ac', accent: '#6b4a2a' },
    hint: 'Deer come out of deep woodland at first light, and only if nobody is about.',
    size: 2,
  },
  fox: {
    id: 'fox',
    name: 'Fox',
    plural: 'Foxes',
    habitat: { forest: 1.0, meadow: 0.5, grass: 0.3 },
    likesProps: { bush: 0.6, tree: 0.4 },
    active: [0.72, 0.99],
    density: 0.005,
    hardCap: 2,
    speed: 2.0,
    skittish: 5.0,
    rarity: 3,
    colors: { body: '#d2703a', belly: '#f2e8dc', accent: '#8c3f1c' },
    hint: 'A fox will cross the kingdom at night, and never twice by the same route.',
    size: 1,
  },
  owl: {
    id: 'owl',
    name: 'Snowy Owl',
    plural: 'Snowy Owls',
    habitat: { forest: 1.0, meadow: 0.6, rocky: 0.5 },
    likesProps: { tree: 1.0 },
    active: [0.74, 0.99],
    density: 0.004,
    hardCap: 1,
    speed: 1.6,
    skittish: 4.0,
    rarity: 3.5,
    colors: { body: '#efeae2', belly: '#ffffff', accent: '#b8ae9e' },
    hint: 'Snowy owls are winter visitors, and they do not visit often.',
    size: 2,
    seasons: ['winter'],
  },
};

export const SPECIES_ORDER = Object.keys(SPECIES) as SpeciesId[];
